-- ElvUI Profile Data
-- This file contains the exported ElvUI profile data

local ProfileData = {
    profileKeys = {
        -- Character profiles will be automatically added when users install
        -- Format: ["CharacterName - ServerName"] = "Norn Edit"
    },
    
    profiles = {
        ["Norn Edit"] = {
                ["actionbar"] = {
                    ["bar1"] = {
                        ["buttonSize"] = 36,
                        ["buttonSpacing"] = 4,
                        ["visibility"] = "[modifier:alt] show; hide",
                    },
                    ["bar2"] = {
                        ["buttonSize"] = 48,
                        ["buttonSpacing"] = 4,
                        ["buttonsPerRow"] = 6,
                    },
                    ["bar3"] = {
                        ["buttonSize"] = 36,
                        ["buttonSpacing"] = 4,
                        ["buttons"] = 12,
                        ["buttonsPerRow"] = 12,
                        ["visibility"] = "[modifier:alt] show; hide",
                    },
                    ["bar4"] = {
                        ["backdrop"] = false,
                        ["buttonSize"] = 36,
                        ["buttonSpacing"] = 4,
                        ["buttons"] = 6,
                        ["buttonsPerRow"] = 6,
                        ["visibility"] = "[modifier:alt] show; hide",
                    },
                    ["bar5"] = {
                        ["alpha"] = 0.5,
                        ["buttonSize"] = 44,
                        ["buttonSpacing"] = 4,
                        ["visibility"] = "[vehicleui][petbattle][overridebar][combat] hide; show",
                    },
                    ["bar6"] = {
                        ["buttonSize"] = 36,
                        ["buttonSpacing"] = 4,
                        ["enabled"] = true,
                        ["visibility"] = "[modifier:alt] show; hide",
                    },
                    ["barPet"] = {
                        ["enabled"] = false,
                    },
                    ["font"] = "Albertus Nova Bold",
                    ["stanceBar"] = {
                        ["enabled"] = false,
                    },
                },
                ["auras"] = {
                    ["buffs"] = {
                        ["countFont"] = "Albertus Nova Bold",
                        ["countFontOutline"] = "SHADOW",
                        ["countFontSize"] = 16,
                        ["countXOffset"] = -2,
                        ["countYOffset"] = 2,
                        ["growthDirection"] = "RIGHT_DOWN",
                        ["size"] = 36,
                        ["timeFont"] = "Albertus Nova Bold",
                        ["timeFontOutline"] = "SHADOW",
                        ["timeFontSize"] = 13,
                        ["timeYOffset"] = -4,
                    },
                    ["debuffs"] = {
                        ["countFont"] = "Albertus Nova Bold",
                        ["countFontOutline"] = "SHADOW",
                        ["countFontSize"] = 12,
                        ["seperateOwn"] = 0,
                        ["sortDir"] = "+",
                        ["timeFont"] = "Albertus Nova Bold",
                        ["timeFontOutline"] = "SHADOW",
                        ["timeFontSize"] = 13,
                        ["timeYOffset"] = -4,
                    },
                },
                ["bags"] = {
                    ["countFont"] = "Albertus Nova Bold",
                    ["countFontSize"] = 12,
                    ["itemLevelFont"] = "Albertus Nova Bold",
                    ["itemLevelFontSize"] = 12,
                    ["vendorGrays"] = {
                        ["details"] = true,
                        ["enable"] = true,
                        ["progressBar"] = false,
                    },
                },
                ["chat"] = {
                    ["font"] = "Albertus Nova Bold",
                    ["fontSize"] = 12,
                    ["hideCopyButton"] = true,
                    ["inactivityTimer"] = 60,
                    ["numAllowedCombatRepeat"] = 2,
                    ["panelBackdrop"] = "HIDEBOTH",
                    ["panelHeight"] = 234,
                    ["panelWidth"] = 500,
                    ["tabFont"] = "Albertus Nova Bold",
                    ["tabFontSize"] = 14,
                    ["tabSelector"] = "NONE",
                },
                ["convertPages"] = true,
                ["databars"] = {
                    ["azerite"] = {
                        ["enable"] = false,
                    },
                    ["experience"] = {
                        ["enable"] = false,
                    },
                    ["honor"] = {
                        ["enable"] = false,
                    },
                    ["threat"] = {
                        ["enable"] = false,
                    },
                },
                ["datatexts"] = {
                    ["font"] = "Albertus Nova Bold",
                    ["fontSize"] = 13,
                    ["panels"] = {
                        ["LeftChatDataPanel"] = {
                            [1] = "Location",
                            ["enable"] = false,
                        },
                        ["Minimap"] = {
                            [1] = "Location",
                            [2] = "NE:FPS",
                            [3] = "NE:MS",
                            [4] = "NE:Dura",
                            [5] = "Time",
                            [6] = "Bags",
                            ["battleground"] = false,
                            ["enable"] = true,
                        },
                        ["MinimapPanel"] = {
                            ["enable"] = false,
                        },
                        ["RightChatDataPanel"] = {
                            ["enable"] = false,
                        },
                        ["Stats"] = {
                            [1] = "NE:Crit",
                            [2] = "NE:Haste",
                            [3] = "NE:Mastery",
                            [4] = "NE:Versatility",
                            ["battleground"] = false,
                            ["enable"] = true,
                        },
                    },
                },
                ["general"] = {
                    ["addonCompartment"] = {
                        ["hide"] = true,
                    },
                    ["afk"] = false,
                    ["afkAnimation"] = "roar",
                    ["afkChat"] = false,
                    ["afkSpin"] = false,
                    ["altPowerBar"] = {
                        ["font"] = "Albertus Nova Bold",
                        ["statusBar"] = "Norn",
                    },
                    ["autoRepair"] = "PLAYER",
                    ["bottomPanel"] = false,
                    ["bottomPanelSettings"] = {
                        ["transparent"] = false,
                    },
                    ["classColors"] = {
                        ["DEMONHUNTER"] = {
                            ["b"] = 0.78039222955704,
                            ["g"] = 0.070588238537312,
                            ["r"] = 0.71372550725937,
                        },
                        ["PALADIN"] = {
                            ["b"] = 0.73725491762161,
                            ["g"] = 0.40392160415649,
                            ["r"] = 0.94901967048645,
                        },
                        ["PRIEST"] = {
                            ["b"] = 0.9215686917305,
                            ["g"] = 0.9215686917305,
                            ["r"] = 0.9215686917305,
                        },
                        ["ROGUE"] = {
                            ["b"] = 0.258823543787,
                            ["g"] = 0.83921575546265,
                            ["r"] = 0.91764712333679,
                        },
                        ["SHAMAN"] = {
                            ["b"] = 0.85882359743118,
                            ["g"] = 0.32549020648003,
                            ["r"] = 0.082352943718433,
                        },
                        ["WARLOCK"] = {
                            ["b"] = 0.92941182851791,
                            ["g"] = 0.45490199327469,
                            ["r"] = 0.54509806632996,
                        },
                        ["WARRIOR"] = {
                            ["b"] = 0.35294118523598,
                            ["g"] = 0.5137255191803,
                            ["r"] = 0.76862752437592,
                        },
                    },
                    ["customGlow"] = {
                        ["style"] = "Proc Glow",
                    },
                    ["font"] = "Albertus Nova Bold",
                    ["fontStyle"] = "SHADOW",
                    ["fonts"] = {
                        ["cooldown"] = {
                            ["font"] = "Albertus Nova Bold",
                            ["outline"] = "SHADOW",
                        },
                        ["worldsubzone"] = {
                            ["enable"] = true,
                            ["font"] = "Albertus Nova Bold",
                            ["outline"] = "SHADOW",
                        },
                        ["worldzone"] = {
                            ["enable"] = true,
                            ["font"] = "Albertus Nova Bold",
                            ["outline"] = "SHADOW",
                        },
                    },
                    ["hideZoneText"] = true,
                    ["itemLevel"] = {
                        ["itemLevelFont"] = "Albertus Nova Bold",
                        ["itemLevelFontOutline"] = "SHADOW",
                        ["itemLevelRarity"] = false,
                        ["totalLevelFont"] = "Albertus Nova Bold",
                        ["totalLevelFontOutline"] = "SHADOW",
                    },
                    ["loginmessage"] = false,
                    ["minimap"] = {
                        ["icons"] = {
                            ["difficulty"] = {
                                ["xOffset"] = 25,
                                ["yOffset"] = -25,
                            },
                        },
                        ["locationFont"] = "Albertus Nova Bold",
                        ["locationText"] = "HIDE",
                        ["resetZoom"] = {
                            ["enable"] = true,
                        },
                        ["size"] = 200,
                    },
                    ["queueStatus"] = {
                        ["enable"] = false,
                        ["font"] = "Albertus Nova Bold",
                        ["scale"] = 0.6,
                    },
                    ["stickyFrames"] = false,
                    ["valuecolor"] = {
                        ["b"] = 1,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                },
                ["movers"] = {
                    ["ArenaHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-685,-483",
                    ["BNETMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,16,270",
                    ["BelowMinimapContainerMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-16,-224",
                    ["BossButton"] = "BOTTOM,ElvUIParent,BOTTOM,0,300",
                    ["BossHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-685,-251",
                    ["BuffsMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,16,-16",
                    ["DTPanelMinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-248,-43",
                    ["DTPanelStatsMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,16",
                    ["DebuffsMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,520,474",
                    ["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,0,64",
                    ["ElvAB_2"] = "BOTTOM,UIParent,BOTTOM,16,58",
                    ["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,0,104",
                    ["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,0,184",
                    ["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,0,16",
                    ["ElvAB_6"] = "BOTTOM,ElvUIParent,BOTTOM,0,144",
                    ["ElvUF_FocusMover"] = "BOTTOM,ElvUIParent,BOTTOM,235,395",
                    ["ElvUF_PartyMover"] = "TOPLEFT,UIParent,TOPLEFT,685,-539",
                    ["ElvUF_PetMover"] = "BOTTOM,UIParent,BOTTOM,-235,395",
                    ["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-235,490",
                    ["ElvUF_Raid1Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,16,474",
                    ["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,235,490",
                    ["ElvUIBagMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-16,16",
                    ["GMMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,570,-16",
                    ["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,16,32",
                    ["LootFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,570,-94",
                    ["LossControlMover"] = "TOP,ElvUIParent,TOP,0,-660",
                    ["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-16,-16",
                    ["PlayerPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-344,293",
                    ["QueueStatusMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-27,-177",
                    ["RightChatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-16,16",
                    ["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-16,16",
                    ["VOICECHAT"] = "TOPLEFT,UIParent,TOPLEFT,570,-121",
                },
                ["nameplates"] = {
                    ["font"] = "Albertus Nova Bold",
                },
                ["tooltip"] = {
                    ["alwaysShowRealm"] = true,
                    ["cursorAnchor"] = true,
                    ["cursorAnchorType"] = "ANCHOR_CURSOR_RIGHT",
                    ["cursorAnchorX"] = 16,
                    ["fadeOut"] = false,
                    ["font"] = "Albertus Nova Bold",
                    ["gender"] = true,
                    ["headerFont"] = "Albertus Nova Bold",
                    ["healthBar"] = {
                        ["font"] = "Albertus Nova Bold",
                        ["statusPosition"] = "DISABLED",
                    },
                    ["modifierID"] = "SHIFT",
                    ["visibility"] = {
                        ["combatOverride"] = "SHIFT",
                    },
                },
                ["unitframe"] = {
                    ["colors"] = {
                        ["castColor"] = {
                            ["b"] = 0.258823543787,
                            ["g"] = 1,
                            ["r"] = 1,
                        },
                        ["castInterruptedColor"] = {
                            ["b"] = 0.20000001788139,
                            ["g"] = 0.258823543787,
                            ["r"] = 1,
                        },
                        ["castNoInterrupt"] = {
                            ["b"] = 0.258823543787,
                            ["g"] = 0.80000007152557,
                            ["r"] = 1,
                        },
                        ["colorhealthbyvalue"] = false,
                        ["frameGlow"] = {
                            ["mouseoverGlow"] = {
                                ["texture"] = "Norn",
                            },
                        },
                        ["healthMultiplier"] = 0.35,
                        ["healthclass"] = true,
                    },
                    ["font"] = "Albertus Nova Bold",
                    ["fontOutline"] = "SHADOW",
                    ["fontSize"] = 12,
                    ["statusbar"] = "Norn",
                    ["units"] = {
                        ["arena"] = {
                            ["buffs"] = {
                                ["enable"] = false,
                                ["maxDuration"] = 0,
                                ["priority"] = "Blacklist,Dispellable,RaidBuffsElvUI",
                                ["sizeOverride"] = 22,
                                ["yOffset"] = 20,
                            },
                            ["castbar"] = {
                                ["icon"] = false,
                                ["overlayOnFrame"] = "Power",
                                ["textColor"] = {
                                    ["b"] = 1,
                                    ["g"] = 1,
                                    ["r"] = 1,
                                },
                                ["width"] = 215,
                                ["yOffsetText"] = -18,
                                ["yOffsetTime"] = -18,
                            },
                            ["customTexts"] = {
                                ["[health]"] = {
                                    ["attachTextTo"] = "Health",
                                    ["enable"] = true,
                                    ["font"] = "Albertus Nova Bold",
                                    ["fontOutline"] = "SHADOW",
                                    ["justifyH"] = "CENTER",
                                    ["size"] = 14,
                                    ["text_format"] = "[health:current:shortvalue]",
                                    ["xOffset"] = 0,
                                    ["yOffset"] = -1,
                                },
                            },
                            ["debuffs"] = {
                                ["desaturate"] = true,
                                ["enable"] = false,
                                ["maxDuration"] = 0,
                                ["sizeOverride"] = 22,
                                ["yOffset"] = -3,
                            },
                            ["disableFocusGlow"] = true,
                            ["disableMouseoverGlow"] = true,
                            ["disableTargetGlow"] = true,
                            ["enable"] = false,
                            ["growthDirection"] = "UP",
                            ["healPrediction"] = {
                                ["enable"] = false,
                            },
                            ["health"] = {
                                ["position"] = "CENTER",
                                ["text_format"] = "",
                                ["xOffset"] = 0,
                            },
                            ["height"] = 32,
                            ["infoPanel"] = {
                                ["height"] = 16,
                            },
                            ["name"] = {
                                ["text_format"] = "[name:abbrev:short]",
                                ["yOffset"] = 19,
                            },
                            ["power"] = {
                                ["height"] = 12,
                                ["smoothbars"] = true,
                                ["text_format"] = "",
                            },
                            ["spacing"] = 45,
                            ["width"] = 128,
                        },
                        ["assist"] = {
                            ["enable"] = false,
                        },
                        ["boss"] = {
                            ["buffIndicator"] = {
                                ["enable"] = false,
                            },
                            ["buffs"] = {
                                ["enable"] = false,
                            },
                            ["castbar"] = {
                                ["icon"] = false,
                                ["overlayOnFrame"] = "Power",
                                ["textColor"] = {
                                    ["b"] = 1,
                                    ["g"] = 1,
                                    ["r"] = 1,
                                },
                                ["yOffsetText"] = -18,
                                ["yOffsetTime"] = -18,
                            },
                            ["customTexts"] = {
                                ["[health]"] = {
                                    ["attachTextTo"] = "Health",
                                    ["enable"] = true,
                                    ["font"] = "Albertus Nova Bold",
                                    ["fontOutline"] = "SHADOW",
                                    ["justifyH"] = "CENTER",
                                    ["size"] = 14,
                                    ["text_format"] = "[health:current:shortvalue]",
                                    ["xOffset"] = 0,
                                    ["yOffset"] = -1,
                                },
                            },
                            ["debuffs"] = {
                                ["enable"] = false,
                            },
                            ["disableFocusGlow"] = true,
                            ["disableMouseoverGlow"] = true,
                            ["disableTargetGlow"] = true,
                            ["growthDirection"] = "UP",
                            ["health"] = {
                                ["position"] = "CENTER",
                                ["text_format"] = "",
                                ["xOffset"] = 0,
                            },
                            ["height"] = 32,
                            ["name"] = {
                                ["text_format"] = "[name:abbrev:short]",
                                ["yOffset"] = 19,
                            },
                            ["power"] = {
                                ["height"] = 12,
                                ["smoothbars"] = true,
                                ["text_format"] = "",
                            },
                            ["privateAuras"] = {
                                ["enable"] = false,
                            },
                            ["raidicon"] = {
                                ["attachTo"] = "TOPLEFT",
                                ["size"] = 16,
                                ["xOffset"] = 1,
                            },
                            ["spacing"] = 45,
                            ["width"] = 128,
                        },
                        ["focus"] = {
                            ["aurabar"] = {
                                ["detachedWidth"] = 270,
                                ["maxBars"] = 6,
                            },
                            ["buffs"] = {
                                ["anchorPoint"] = "TOPLEFT",
                                ["attachTo"] = "DEBUFFS",
                                ["maxDuration"] = 0,
                                ["perrow"] = 8,
                                ["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,NonPersonal",
                            },
                            ["castbar"] = {
                                ["icon"] = false,
                                ["overlayOnFrame"] = "Power",
                                ["smoothbars"] = true,
                                ["textColor"] = {
                                    ["b"] = 1,
                                    ["g"] = 1,
                                    ["r"] = 1,
                                },
                                ["width"] = 128,
                                ["yOffsetText"] = -18,
                                ["yOffsetTime"] = -18,
                            },
                            ["customTexts"] = {
                                ["[health]"] = {
                                    ["attachTextTo"] = "Health",
                                    ["enable"] = true,
                                    ["font"] = "Albertus Nova Bold",
                                    ["fontOutline"] = "SHADOW",
                                    ["justifyH"] = "CENTER",
                                    ["size"] = 14,
                                    ["text_format"] = "[health:current:shortvalue]",
                                    ["xOffset"] = 0,
                                    ["yOffset"] = -1,
                                },
                            },
                            ["debuffs"] = {
                                ["anchorPoint"] = "TOPLEFT",
                                ["enable"] = false,
                                ["growthX"] = "RIGHT",
                                ["maxDuration"] = 0,
                                ["perrow"] = 8,
                                ["priority"] = "Blacklist,Personal,NonPersonal",
                            },
                            ["disableMouseoverGlow"] = true,
                            ["disableTargetGlow"] = true,
                            ["health"] = {
                                ["position"] = "CENTER",
                                ["smoothbars"] = true,
                                ["xOffset"] = 2,
                            },
                            ["height"] = 32,
                            ["infoPanel"] = {
                                ["height"] = 20,
                            },
                            ["name"] = {
                                ["text_format"] = "[name:abbrev:short]",
                                ["yOffset"] = 19,
                            },
                            ["orientation"] = "LEFT",
                            ["power"] = {
                                ["detachedWidth"] = 128,
                                ["height"] = 12,
                                ["position"] = "RIGHT",
                                ["smoothbars"] = true,
                                ["strataAndLevel"] = {
                                    ["frameLevel"] = 14,
                                    ["frameStrata"] = "TOOLTIP",
                                },
                                ["xOffset"] = -2,
                            },
                            ["threatStyle"] = "NONE",
                            ["width"] = 128,
                        },
                        ["party"] = {
                            ["buffIndicator"] = {
                                ["enable"] = false,
                            },
                            ["customTexts"] = {
                                ["[health]"] = {
                                    ["attachTextTo"] = "Health",
                                    ["enable"] = true,
                                    ["font"] = "Albertus Nova Bold",
                                    ["fontOutline"] = "SHADOW",
                                    ["justifyH"] = "CENTER",
                                    ["size"] = 14,
                                    ["text_format"] = "[health:current:shortvalue]",
                                    ["xOffset"] = 0,
                                    ["yOffset"] = -1,
                                },
                            },
                            ["debuffs"] = {
                                ["enable"] = false,
                            },
                            ["disableFocusGlow"] = true,
                            ["disableMouseoverGlow"] = true,
                            ["disableTargetGlow"] = true,
                            ["groupBy"] = "ROLE",
                            ["health"] = {
                                ["position"] = "CENTER",
                                ["smoothbars"] = true,
                                ["text_format"] = "",
                                ["xOffset"] = 0,
                            },
                            ["height"] = 32,
                            ["name"] = {
                                ["text_format"] = "[name:veryshort:translit]",
                                ["yOffset"] = 19,
                            },
                            ["power"] = {
                                ["height"] = 12,
                                ["smoothbars"] = true,
                                ["text_format"] = "",
                            },
                            ["privateAuras"] = {
                                ["enable"] = false,
                            },
                            ["raidRoleIcons"] = {
                                ["scale"] = 1.4,
                                ["xOffset"] = 1,
                                ["yOffset"] = 8,
                            },
                            ["raidicon"] = {
                                ["attachTo"] = "TOPLEFT",
                                ["attachToObject"] = "Health",
                                ["size"] = 16,
                                ["xOffset"] = 19,
                                ["yOffset"] = 19,
                            },
                            ["rdebuffs"] = {
                                ["enable"] = false,
                                ["font"] = "Albertus Nova Bold",
                            },
                            ["readycheckIcon"] = {
                                ["attachTo"] = "Frame",
                                ["position"] = "RIGHT",
                                ["size"] = 24,
                                ["xOffset"] = 24,
                                ["yOffset"] = 0,
                            },
                            ["resurrectIcon"] = {
                                ["attachTo"] = "RIGHT",
                                ["attachToObject"] = "Health",
                                ["size"] = 20,
                                ["xOffset"] = 10,
                            },
                            ["roleIcon"] = {
                                ["damager"] = false,
                                ["position"] = "TOPRIGHT",
                                ["size"] = 16,
                                ["xOffset"] = -3,
                                ["yOffset"] = 19,
                            },
                            ["showPlayer"] = false,
                            ["threatStyle"] = "NONE",
                            ["verticalSpacing"] = 30,
                            ["width"] = 128,
                        },
                        ["pet"] = {
                            ["aurabar"] = {
                                ["attachTo"] = "DEBUFFS",
                                ["detachedWidth"] = 270,
                                ["priority"] = "Blacklist,blockNoDuration,Personal,RaidDebuffs",
                                ["spacing"] = 0,
                                ["yOffset"] = 0,
                            },
                            ["buffs"] = {
                                ["anchorPoint"] = "TOPLEFT",
                                ["attachTo"] = "DEBUFFS",
                                ["maxDuration"] = 0,
                                ["perrow"] = 8,
                                ["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,NonPersonal",
                            },
                            ["castbar"] = {
                                ["icon"] = false,
                                ["overlayOnFrame"] = "Power",
                                ["smoothbars"] = true,
                                ["textColor"] = {
                                    ["b"] = 1,
                                    ["g"] = 1,
                                    ["r"] = 1,
                                },
                                ["width"] = 128,
                                ["yOffsetText"] = -18,
                                ["yOffsetTime"] = -18,
                            },
                            ["customTexts"] = {
                                ["[health]"] = {
                                    ["attachTextTo"] = "Health",
                                    ["enable"] = true,
                                    ["font"] = "Albertus Nova Bold",
                                    ["fontOutline"] = "SHADOW",
                                    ["justifyH"] = "CENTER",
                                    ["size"] = 14,
                                    ["text_format"] = "[health:current:shortvalue]",
                                    ["xOffset"] = 0,
                                    ["yOffset"] = -1,
                                },
                            },
                            ["debuffs"] = {
                                ["anchorPoint"] = "TOPLEFT",
                                ["growthX"] = "RIGHT",
                                ["maxDuration"] = 0,
                                ["perrow"] = 8,
                                ["priority"] = "Blacklist,Personal,NonPersonal",
                            },
                            ["disableMouseoverGlow"] = true,
                            ["health"] = {
                                ["position"] = "CENTER",
                                ["smoothbars"] = true,
                                ["xOffset"] = 2,
                            },
                            ["height"] = 32,
                            ["infoPanel"] = {
                                ["height"] = 20,
                            },
                            ["name"] = {
                                ["text_format"] = "[name:abbrev:short]",
                                ["yOffset"] = 19,
                            },
                            ["orientation"] = "LEFT",
                            ["power"] = {
                                ["detachedWidth"] = 128,
                                ["height"] = 12,
                                ["position"] = "RIGHT",
                                ["smoothbars"] = true,
                                ["strataAndLevel"] = {
                                    ["frameLevel"] = 14,
                                    ["frameStrata"] = "TOOLTIP",
                                },
                                ["xOffset"] = -2,
                            },
                            ["threatStyle"] = "NONE",
                            ["width"] = 128,
                        },
                        ["player"] = {
                            ["CombatIcon"] = {
                                ["enable"] = false,
                            },
                            ["RestIcon"] = {
                                ["enable"] = false,
                            },
                            ["aurabar"] = {
                                ["enable"] = false,
                            },
                            ["castbar"] = {
                                ["icon"] = false,
                                ["latency"] = false,
                                ["overlayOnFrame"] = "Power",
                                ["smoothbars"] = true,
                                ["textColor"] = {
                                    ["b"] = 1,
                                    ["g"] = 1,
                                    ["r"] = 1,
                                },
                                ["width"] = 128,
                                ["yOffsetText"] = -18,
                                ["yOffsetTime"] = -18,
                            },
                            ["classbar"] = {
                                ["enable"] = false,
                            },
                            ["customTexts"] = {
                                ["[health]"] = {
                                    ["attachTextTo"] = "Health",
                                    ["enable"] = true,
                                    ["font"] = "Albertus Nova Bold",
                                    ["fontOutline"] = "SHADOW",
                                    ["justifyH"] = "CENTER",
                                    ["size"] = 14,
                                    ["text_format"] = "[health:current:shortvalue]",
                                    ["xOffset"] = 0,
                                    ["yOffset"] = -1,
                                },
                            },
                            ["debuffs"] = {
                                ["enable"] = false,
                            },
                            ["disableMouseoverGlow"] = true,
                            ["health"] = {
                                ["position"] = "CENTER",
                                ["smoothbars"] = true,
                                ["text_format"] = "",
                            },
                            ["height"] = 32,
                            ["name"] = {
                                ["text_format"] = "[name]",
                                ["yOffset"] = 19,
                            },
                            ["power"] = {
                                ["detachedWidth"] = 128,
                                ["height"] = 12,
                                ["smoothbars"] = true,
                                ["strataAndLevel"] = {
                                    ["frameLevel"] = 14,
                                    ["frameStrata"] = "TOOLTIP",
                                },
                                ["text_format"] = "",
                            },
                            ["raidRoleIcons"] = {
                                ["scale"] = 1.4,
                                ["yOffset"] = 8,
                            },
                            ["raidicon"] = {
                                ["attachTo"] = "TOPLEFT",
                                ["attachToObject"] = "Health",
                                ["size"] = 16,
                                ["xOffset"] = 16,
                                ["yOffset"] = 18,
                            },
                            ["threatStyle"] = "NONE",
                            ["width"] = 128,
                        },
                        ["raid1"] = {
                            ["buffIndicator"] = {
                                ["enable"] = false,
                            },
                            ["customTexts"] = {
                                ["[health]"] = {
                                    ["attachTextTo"] = "Health",
                                    ["enable"] = true,
                                    ["font"] = "Albertus Nova Bold",
                                    ["fontOutline"] = "SHADOW",
                                    ["justifyH"] = "CENTER",
                                    ["size"] = 14,
                                    ["text_format"] = "[health:current:shortvalue]",
                                    ["xOffset"] = 0,
                                    ["yOffset"] = -1,
                                },
                            },
                            ["debuffHighlight"] = {
                                ["enable"] = false,
                            },
                            ["disableFocusGlow"] = true,
                            ["disableMouseoverGlow"] = true,
                            ["disableTargetGlow"] = true,
                            ["groupsPerRowCol"] = 2,
                            ["growthDirection"] = "UP_RIGHT",
                            ["health"] = {
                                ["smoothbars"] = true,
                                ["text_format"] = "",
                            },
                            ["height"] = 32,
                            ["horizontalSpacing"] = 60,
                            ["name"] = {
                                ["text_format"] = "[name:short]",
                                ["yOffset"] = 19,
                            },
                            ["numGroups"] = 6,
                            ["power"] = {
                                ["height"] = 12,
                                ["smoothbars"] = true,
                            },
                            ["privateAuras"] = {
                                ["enable"] = false,
                            },
                            ["raidRoleIcons"] = {
                                ["scale"] = 1.4,
                                ["xOffset"] = 1,
                                ["yOffset"] = 8,
                            },
                            ["raidicon"] = {
                                ["attachTo"] = "TOPLEFT",
                                ["attachToObject"] = "Health",
                                ["size"] = 16,
                                ["xOffset"] = 19,
                                ["yOffset"] = 19,
                            },
                            ["rdebuffs"] = {
                                ["enable"] = false,
                                ["font"] = "Albertus Nova Bold",
                            },
                            ["readycheckIcon"] = {
                                ["attachTo"] = "Frame",
                                ["position"] = "RIGHT",
                                ["size"] = 24,
                                ["xOffset"] = 24,
                                ["yOffset"] = 0,
                            },
                            ["roleIcon"] = {
                                ["damager"] = false,
                                ["position"] = "TOPRIGHT",
                                ["size"] = 16,
                                ["xOffset"] = -3,
                                ["yOffset"] = 19,
                            },
                            ["threatStyle"] = "ICONTOPLEFT",
                            ["verticalSpacing"] = 20,
                            ["visibility"] = "[@raid6,noexists][@raid31,exists] hide;show",
                            ["width"] = 128,
                        },
                        ["raid2"] = {
                            ["enable"] = false,
                            ["rdebuffs"] = {
                                ["font"] = "Albertus Nova Bold",
                            },
                        },
                        ["raid3"] = {
                            ["enable"] = false,
                            ["rdebuffs"] = {
                                ["font"] = "Albertus Nova Bold",
                            },
                        },
                        ["tank"] = {
                            ["enable"] = false,
                        },
                        ["target"] = {
                            ["CombatIcon"] = {
                                ["enable"] = false,
                            },
                            ["aurabar"] = {
                                ["enable"] = false,
                            },
                            ["auras"] = {
                                ["anchorPoint"] = "TOPLEFT",
                                ["enable"] = false,
                                ["filter"] = "HELPFUL",
                                ["perrow"] = 8,
                                ["priority"] = "",
                                ["sizeOverride"] = 0,
                                ["xOffset"] = 0,
                            },
                            ["buffs"] = {
                                ["anchorPoint"] = "TOPLEFT",
                                ["attachTo"] = "DEBUFFS",
                                ["enable"] = false,
                                ["growthX"] = "RIGHT",
                                ["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,NonPersonal",
                            },
                            ["castbar"] = {
                                ["icon"] = false,
                                ["overlayOnFrame"] = "Power",
                                ["smoothbars"] = true,
                                ["textColor"] = {
                                    ["b"] = 1,
                                    ["g"] = 1,
                                    ["r"] = 1,
                                },
                                ["width"] = 128,
                                ["yOffsetText"] = -18,
                                ["yOffsetTime"] = -18,
                            },
                            ["customTexts"] = {
                                ["[health]"] = {
                                    ["attachTextTo"] = "Health",
                                    ["enable"] = true,
                                    ["font"] = "Albertus Nova Bold",
                                    ["fontOutline"] = "SHADOW",
                                    ["justifyH"] = "CENTER",
                                    ["size"] = 14,
                                    ["text_format"] = "[health:current:shortvalue]",
                                    ["xOffset"] = 0,
                                    ["yOffset"] = -1,
                                },
                            },
                            ["debuffs"] = {
                                ["anchorPoint"] = "TOPLEFT",
                                ["attachTo"] = "FRAME",
                                ["enable"] = false,
                                ["growthX"] = "RIGHT",
                                ["maxDuration"] = 0,
                                ["priority"] = "Blacklist,Personal,NonPersonal",
                            },
                            ["disableMouseoverGlow"] = true,
                            ["health"] = {
                                ["position"] = "CENTER",
                                ["smoothbars"] = true,
                                ["text_format"] = "",
                                ["xOffset"] = 2,
                            },
                            ["height"] = 32,
                            ["name"] = {
                                ["text_format"] = "[name:abbrev:short]",
                                ["yOffset"] = 19,
                            },
                            ["orientation"] = "LEFT",
                            ["power"] = {
                                ["detachedWidth"] = 128,
                                ["height"] = 12,
                                ["position"] = "RIGHT",
                                ["smoothbars"] = true,
                                ["strataAndLevel"] = {
                                    ["frameLevel"] = 14,
                                    ["frameStrata"] = "TOOLTIP",
                                },
                                ["text_format"] = "",
                                ["xOffset"] = -2,
                            },
                            ["raidRoleIcons"] = {
                                ["scale"] = 1.4,
                                ["xOffset"] = 1,
                                ["yOffset"] = 8,
                            },
                            ["raidicon"] = {
                                ["attachTo"] = "TOPRIGHT",
                                ["attachToObject"] = "Health",
                                ["size"] = 16,
                                ["xOffset"] = -4,
                                ["yOffset"] = 19,
                            },
                            ["threatStyle"] = "NONE",
                            ["width"] = 128,
                        },
                        ["targettarget"] = {
                            ["enable"] = false,
                        },
                    },
                },
        },
    },
    
    global = {
        ["datatexts"] = {
            ["customPanels"] = {
                ["Minimap"] = {
                    ["backdrop"] = false,
                    ["border"] = false,
                    ["font"] = "Albertus Nova Bold",
                    ["fontOutline"] = "SHADOW",
                    ["fontSize"] = 13,
                    ["growth"] = "VERTICAL",
                    ["height"] = 150,
                    ["name"] = "Minimap",
                    ["numPoints"] = 6,
                    ["textJustify"] = "RIGHT",
                    ["width"] = 360,
                },
                ["Stats"] = {
                    ["backdrop"] = false,
                    ["border"] = false,
                    ["height"] = 24,
                    ["name"] = "Stats",
                    ["numPoints"] = 4,
                    ["visibility"] = "[combat] show;hide",
                    ["width"] = 700,
                    ["growth"] = "HORIZONTAL",
                    ["textJustify"] = "CENTER",
                    ["font"] = "Albertus Nova Bold",
                    ["fontOutline"] = "SHADOW",
                    ["fontSize"] = 13,
                },
            },
            ["settings"] = {
                ["Bags"] = {
                    ["NoLabel"] = true,
                },
                ["Location"] = {
                    ["showZone"] = false,
                },
            },
        },
    },
    
    private = {
        ["Norn Edit"] = {
                ["actionbar"] = {
                    ["masque"] = {
                        ["actionbars"] = true,
                    },
                },
                ["auras"] = {
                    ["masque"] = {
                        ["buffs"] = true,
                        ["debuffs"] = true,
                    },
                },
                ["bags"] = {
                    ["enable"] = false,
                },
                ["general"] = {
                    ["blizzardFontSize"] = true,
                    ["chatBubbleFont"] = "Albertus Nova Bold",
                    ["chatBubbleFontOutline"] = "SHADOW",
                    ["chatBubbles"] = "disabled",
                    ["classColors"] = true,
                    ["dmgfont"] = "Albertus Nova Bold",
                    ["glossTex"] = "Norn",
                    ["minimap"] = {
                        ["hideClassHallReport"] = true,
                        ["hideTracking"] = true,
                    },
                    ["namefont"] = "Albertus Nova Bold",
                    ["nameplateFont"] = "Albertus Nova Bold",
                    ["nameplateFontOutline"] = "SHADOW",
                    ["nameplateFontSize"] = 13,
                    ["nameplateLargeFont"] = "Albertus Nova Bold",
                    ["nameplateLargeFontOutline"] = "SHADOW",
                    ["nameplateLargeFontSize"] = 16,
                    ["normTex"] = "Norn",
                    ["totemTracker"] = false,
                },
                ["install_complete"] = 14.01,
                ["nameplates"] = {
                    ["enable"] = false,
                },
                ["skins"] = {
                    ["ace3Enable"] = false,
                    ["blizzard"] = {
                        ["achievement"] = false,
                        ["addonManager"] = false,
                        ["adventureMap"] = false,
                        ["alertframes"] = false,
                        ["alliedRaces"] = false,
                        ["animaDiversion"] = false,
                        ["archaeology"] = false,
                        ["arena"] = false,
                        ["arenaRegistrar"] = false,
                        ["artifact"] = false,
                        ["auctionhouse"] = false,
                        ["azerite"] = false,
                        ["azeriteEssence"] = false,
                        ["azeriteRespec"] = false,
                        ["bags"] = false,
                        ["barber"] = false,
                        ["battlefield"] = false,
                        ["bgmap"] = false,
                        ["bgscore"] = false,
                        ["binding"] = false,
                        ["blizzardOptions"] = false,
                        ["bmah"] = false,
                        ["calendar"] = false,
                        ["campsites"] = false,
                        ["channels"] = false,
                        ["character"] = false,
                        ["chromieTime"] = false,
                        ["collections"] = false,
                        ["communities"] = false,
                        ["contribution"] = false,
                        ["cooldownManager"] = false,
                        ["covenantPreview"] = false,
                        ["covenantRenown"] = false,
                        ["covenantSanctum"] = false,
                        ["craft"] = false,
                        ["deathRecap"] = false,
                        ["debug"] = false,
                        ["dressingroom"] = false,
                        ["editor"] = false,
                        ["enable"] = false,
                        ["encounterjournal"] = false,
                        ["engraving"] = false,
                        ["eventLog"] = false,
                        ["expansionLanding"] = false,
                        ["friends"] = false,
                        ["garrison"] = false,
                        ["gbank"] = false,
                        ["genericTrait"] = false,
                        ["gmChat"] = false,
                        ["gossip"] = false,
                        ["greeting"] = false,
                        ["guide"] = false,
                        ["guild"] = false,
                        ["guildBank"] = false,
                        ["guildcontrol"] = false,
                        ["guildregistrar"] = false,
                        ["help"] = false,
                        ["inspect"] = false,
                        ["islandQueue"] = false,
                        ["islandsPartyPose"] = false,
                        ["itemInteraction"] = false,
                        ["itemUpgrade"] = false,
                        ["lfg"] = false,
                        ["lfguild"] = false,
                        ["loot"] = false,
                        ["losscontrol"] = false,
                        ["macro"] = false,
                        ["mail"] = false,
                        ["majorFactions"] = false,
                        ["merchant"] = false,
                        ["mirrorTimers"] = false,
                        ["misc"] = false,
                        ["nonraid"] = false,
                        ["objectiveTracker"] = false,
                        ["obliterum"] = false,
                        ["orderhall"] = false,
                        ["perks"] = false,
                        ["petbattleui"] = false,
                        ["petition"] = false,
                        ["playerChoice"] = false,
                        ["pvp"] = false,
                        ["quest"] = false,
                        ["questChoice"] = false,
                        ["questTimers"] = false,
                        ["raid"] = false,
                        ["reforge"] = false,
                        ["runeforge"] = false,
                        ["scrapping"] = false,
                        ["socket"] = false,
                        ["soulbinds"] = false,
                        ["spellbook"] = false,
                        ["stable"] = false,
                        ["subscriptionInterstitial"] = false,
                        ["tabard"] = false,
                        ["talent"] = false,
                        ["talkinghead"] = false,
                        ["taxi"] = false,
                        ["timemanager"] = false,
                        ["tooltip"] = false,
                        ["torghastLevelPicker"] = false,
                        ["trade"] = false,
                        ["tradeskill"] = false,
                        ["trainer"] = false,
                        ["transmogrify"] = false,
                        ["tutorials"] = false,
                        ["weeklyRewards"] = false,
                        ["worldmap"] = false,
                    },
                    ["checkBoxSkin"] = false,
                    ["libDropdown"] = false,
                },
            },
        },
}
-- Export the profile data
ElvUI_NornEdit_ProfileData = ProfileData

